server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access-secret: access-secret-access-secret-123456
  refresh-secret: refresh-secret-refresh-secret-123456
  access-expiration: 3600
  refresh-expiration: 604800

management:
  endpoints:
    web:
      exposure:
        include: prometheus