version: "3.9"

services:

  identity-db:
    image: postgres:16
    container_name: identity-db
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  passengers-db:
    image: postgres:16
    container_name: passengers-db
    environment:
      POSTGRES_DB: passengers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  identity-service:
    build: ./identity-service
    ports:
      - "8081:8081"
    depends_on:
      - identity-db
    environment:
      SPRING_PROFILES_ACTIVE: seed
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity-db:5432/identity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  passengers-service:
    build: ./passenger-service
    ports:
      - "8082:8082"
    depends_on:
      - passengers-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passengers-db:5432/passengers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - identity-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    depends_on:
      - gateway-service
      - identity-service
      - passengers-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"


volumes:
  grafana-data: